@startuml diagmodif
title Diagramme d'Activité : Modifier un album (admin)

|Admin|
start
:Clique sur le panel Admin;
|#AntiqueWhite|Serveur Web|
if (Vérifie le rôle admin) is (si non) then
  |Admin|
  #red:**Envoi message d'erreur : accès refusé**;
  stop
else (si oui)
:Connecte en tant qu'Admin;
  |Admin|
  :Affiche le panel admin;
  :Clique sur Modifier un album;
  |Serveur Web|
  :Envoi la requête en BDD;
  :l'album existe?;
  if () is (Artciel non trouvé) then
  |Admin|
  #red:**Envoi message d'erreur : album introuvable**;
  stop
 else (Album trouvé)
   |Serveur Web|
   :Récupère les données de l'album;
   |Admin|
   :Affiche le formulaire de modification;
   :Saisit les nouvelles données;
   |BDD|
   :Valide les données saisie;
   if () is (Données Invalides) then
   |Admin|
   #red: **Affiche message d'erreur : champs invalides**;
   stop
 else (Données valides)
   |Serveur Web|
   :Modifie l'album en BDD;
   |Admin|
   :Affiche meessage : album modifié avec succés;
   stop

   @enduml